# Generated by Django 3.2.7 on 2023-01-27 17:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0003_like_match_message_recharge_rooms'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recharge',
            old_name='name',
            new_name='target',
        ),
        migrations.AddField(
            model_name='recharge',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
