# Generated by Django 3.2.7 on 2023-01-27 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20230127_2327'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recharge',
            old_name='target',
            new_name='name',
        ),
    ]
