# Generated by Django 3.2.7 on 2023-01-28 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20230128_1523'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='targetuser',
        ),
        migrations.AddField(
            model_name='match',
            name='sssss',
            field=models.ManyToManyField(to='api.Recharge'),
        ),
    ]
