# Generated by Django 3.2.7 on 2023-01-28 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20230128_1533'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recharge',
            name='name',
        ),
    ]
