# Generated by Django 3.2.7 on 2023-01-28 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remove_recharge_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rooms',
            name='description',
        ),
        migrations.RemoveField(
            model_name='rooms',
            name='targetuser',
        ),
    ]
