# Generated by Django 3.2.7 on 2023-01-28 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20230128_1536'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recharge',
            name='subscriber',
        ),
        migrations.AlterField(
            model_name='match',
            name='sssss',
            field=models.ManyToManyField(to='api.Like'),
        ),
        migrations.DeleteModel(
            name='completercharge',
        ),
    ]
