# Generated by Django 3.2.7 on 2023-01-28 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20230128_1539'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='sssss',
            new_name='likes',
        ),
    ]
