# Generated by Django 3.2.7 on 2023-01-28 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_rename_sssss_match_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='recharge',
            name='taget',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
