# Generated by Django 3.2.7 on 2023-01-30 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_auto_20230130_1712'),
    ]

    operations = [
        migrations.RenameField(
            model_name='img',
            old_name='profile_pic',
            new_name='img',
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(null=True, upload_to='static/profilepictures'),
        ),
    ]
