# Generated by Django 3.1.4 on 2023-01-30 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_auto_20230130_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='img',
            name='user',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
