# Generated by Django 3.2.7 on 2023-01-30 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_auto_20230130_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='img',
            name='user',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
