# Generated by Django 3.2.7 on 2023-01-30 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_auto_20230130_2200'),
    ]

    operations = [
        migrations.RenameField(
            model_name='img',
            old_name='user',
            new_name='host',
        ),
        migrations.RenameField(
            model_name='recharge',
            old_name='host',
            new_name='users',
        ),
    ]
