# Generated by Django 3.2.7 on 2023-01-30 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_auto_20230130_2216'),
    ]

    operations = [
        migrations.RenameField(
            model_name='img',
            old_name='host',
            new_name='user',
        ),
    ]
