# Generated by Django 3.2.7 on 2023-01-30 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_rename_host_img_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='img',
            name='user',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
