# Generated by Django 3.2.7 on 2023-01-31 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_alter_img_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='pp',
        ),
    ]
